export OPENSHIFT_MYSQL_DB_USERNAME="adminE8P5YDz"
export OPENSHIFT_MYSQL_DB_HOST="10.51.177.158"
#export OPENSHIFT_MYSQL_DB_HOST="10.0.0.6"
#export OPENSHIFT_MYSQL_DB_HOST="localhost"
export OPENSHIFT_MYSQL_DB_PORT=3306
export OPENSHIFT_MYSQL_DB_PASSWORD="pd-4H__EyW2v"

#-DOPENSHIFT_MYSQL_DB_HOST=127.4.84.2 
